apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service_template.fullname" . }}-volume
  labels:
    {{- include "service_template.labels" . | nindent 4 }}
type: Opaque
data:

{{- range $key, $val := .Values.secrets_volume }}
  {{ $key }}: {{ $val | b64enc | quote }}    
{{- end}}